[build]
  command = "npm run build"
  publish = "public"  # public 폴더를 배포하도록 설정
  ignore = ""

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 