[build]
  command = "npm run build"
  publish = "dist"
  ignore = ""

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

[[publish]]
  path = "data/daily" 