name: Test Login Page

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        pip install selenium webdriver_manager pandas
    
    - name: Run test
      run: python src/collector/test_login.py
      
    - name: Show test results
      if: always()
      run: |
        echo "=== HTML Files ==="
        for f in log/*.html; do
          echo "=== $f ==="
          cat "$f"
          echo
        done
        
        echo "=== Log Files ==="
        for f in log/*.txt; do
          echo "=== $f ==="
          cat "$f"
          echo
        done 