name: Collect Coupang Ad Data

on:
  schedule:
    - cron: '0 * * * *'  # 매시 정각
  workflow_dispatch:      # 수동 실행 가능

jobs:
  collect:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver_manager
        
    - name: Run collector
      run: python src/collector/main.py
        
    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add data/daily/
        git diff --quiet && git diff --staged --quiet || git commit -m "Update data: $(date '+%Y-%m-%d %H:%M:%S')"
        git push 